#! /usr/bin/env bash
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
create table
  ishikawa_landing_raw_data (
    year text,
    district_cd text,
    district_name text,
    fishing_cd text,
    fishing_name text,
    stock_cd text,
    stock_name text,
    quantity_january text,
    quantity_february text,
    quantity_march text,
    quantity_april text,
    quantity_may text,
    quantity_june text,
    quantity_july text,
    quantity_august text,
    quantity_september text,
    quantity_october text,
    quantity_november text,
    quantity_december text,
    quantity_total text,
    amount_january text,
    amount_february text,
    amount_march text,
    amount_april text,
    amount_may text,
    amount_june text,
    amount_july text,
    amount_august text,
    amount_september text,
    amount_october text,
    amount_november text,
    amount_december text,
    amount_total text
  );
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -c "\copy ishikawa_landing_raw_data from "/docker-entrypoint-initdb.d/石川県水揚げデータ_2025_12_18.csv" with (format csv, header true, encoding 'utf8')"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
create table
  districts (
    district_cd int primary key,
    district_name text not null
  );

create table
  fishing_categories (
    fishing_category_cd int primary key,
    fishing_category_name text not null
  );

create table
  stocks (
    stock_cd int primary key,
    stock_name text not null
  );

create table
  landing (
    id int generated by default as identity primary key,
    year int not null,
    month int not null,
    check (month between 1 and 12),
    district_cd int not null,
    fishing_category_cd int not null,
    stock_cd int not null,
    quantity int not null,
    amount numeric(12, 2) not null,
    foreign key (district_cd) references districts (district_cd),
    foreign key (fishing_category_cd) references fishing_categories (fishing_category_cd),
    foreign key (stock_cd) references stocks (stock_cd)
  );

insert into
  districts (district_cd, district_name)
select distinct
  cast(district_cd as integer),
  trim(district_name)
from
  ishikawa_landing_raw_data
order by
  district_cd asc on conflict (district_cd)
do
  nothing;

insert into
  fishing_categories (fishing_category_cd, fishing_category_name)
select distinct
  cast(fishing_cd as integer),
  trim(fishing_name)
from
  ishikawa_landing_raw_data
order by
  fishing_cd on conflict (fishing_category_cd)
do
  nothing;

insert into
  stocks (stock_cd, stock_name)
select distinct
  cast(stock_cd as integer),
  trim(stock_name)
from
  ishikawa_landing_raw_data
order by
  stock_cd on conflict (stock_cd)
do
  nothing;

insert into
  landing (
    year,
    month,
    district_cd,
    fishing_category_cd,
    stock_cd,
    quantity,
    amount
  )
select
  cast(year as integer),
  cast(month as integer),
  cast(district_cd as integer),
  cast(fishing_cd as integer),
  cast(stock_cd as integer),
  cast(quantity as numeric),
  cast(amount as integer)
from
  (
    select
      year,
      '1' as month,
      district_cd,
      fishing_cd,
      stock_cd,
      quantity_january as quantity,
      amount_january as amount
    from
      ishikawa_landing_raw_data
    union
    select
      year,
      '2' as month,
      district_cd,
      fishing_cd,
      stock_cd,
      quantity_february as quantity,
      amount_february as amount
    from
      ishikawa_landing_raw_data
    union
    select
      year,
      '3' as month,
      district_cd,
      fishing_cd,
      stock_cd,
      quantity_march as quantity,
      amount_march as amount
    from
      ishikawa_landing_raw_data
    union
    select
      year,
      '4' as month,
      district_cd,
      fishing_cd,
      stock_cd,
      quantity_april as quantity,
      amount_april as amount
    from
      ishikawa_landing_raw_data
    union
    select
      year,
      '5' as month,
      district_cd,
      fishing_cd,
      stock_cd,
      quantity_may as quantity,
      amount_may as amount
    from
      ishikawa_landing_raw_data
    union
    select
      year,
      '6' as month,
      district_cd,
      fishing_cd,
      stock_cd,
      quantity_june as quantity,
      amount_june as amount
    from
      ishikawa_landing_raw_data
    union
    select
      year,
      '7' as month,
      district_cd,
      fishing_cd,
      stock_cd,
      quantity_july as quantity,
      amount_july as amount
    from
      ishikawa_landing_raw_data
    union
    select
      year,
      '8' as month,
      district_cd,
      fishing_cd,
      stock_cd,
      quantity_august as quantity,
      amount_august as amount
    from
      ishikawa_landing_raw_data
    union
    select
      year,
      '9' as month,
      district_cd,
      fishing_cd,
      stock_cd,
      quantity_september as quantity,
      amount_september as amount
    from
      ishikawa_landing_raw_data
    union
    select
      year,
      '10' as month,
      district_cd,
      fishing_cd,
      stock_cd,
      quantity_october as quantity,
      amount_october as amount
    from
      ishikawa_landing_raw_data
    union
    select
      year,
      '11' as month,
      district_cd,
      fishing_cd,
      stock_cd,
      quantity_november as quantity,
      amount_november as amount
    from
      ishikawa_landing_raw_data
    union
    select
      year,
      '12' as month,
      district_cd,
      fishing_cd,
      stock_cd,
      quantity_december as quantity,
      amount_december as amount
    from
      ishikawa_landing_raw_data
    order by
      year,
      month,
      district_cd,
      fishing_cd,
      stock_cd
  )
EOSQL
