create table
  kanazawa_market_salted_dried_fish_raw_data (
    year text,
    product_name text,
    producing_area text,
    quantity text,
    amount text,
    average_unit_price text
  );

copy
  kanazawa_market_salted_dried_fish_raw_data
from
  '/docker-entrypoint-initdb.d/金沢市中央卸売市場_水産物部_塩干.csv'
with
  (format csv, header true, encoding 'utf8');

create table
  kanazawa_market_freeze_fish_raw_data (
    year text,
    product_name text,
    producing_area text,
    quantity text,
    amount text,
    average_unit_price text
  );

copy
  kanazawa_market_freeze_fish_raw_data
from
  '/docker-entrypoint-initdb.d/金沢市中央卸売市場_水産物部_冷凍魚.csv'
with
  (format csv, header true, encoding 'utf8');

create table
  kanazawa_market_fresh_fish_raw_data (
    year text,
    product_name text,
    producing_area text,
    quantity text,
    amount text,
    average_unit_price text
  );

copy
  kanazawa_market_fresh_fish_raw_data
from
  '/docker-entrypoint-initdb.d/金沢市中央卸売市場_水産物部_鮮魚.csv'
with
  (format csv, header true, encoding 'utf8');

create table
  prefectures (
    prefecture_id int generated by default as identity primary key,
    name text not null
  );

insert into
  prefectures (name)
select distinct
  producing_area
from
  kanazawa_market_freeze_fish_raw_data
order by
  producing_area;

create table
  products (
    product_id int generated by default as identity primary key,
    name text not null
  );

insert into
  products (name)
select distinct
  product_name
from
  kanazawa_market_freeze_fish_raw_data
union
select distinct
  product_name
from
  kanazawa_market_fresh_fish_raw_data
union
select distinct
  product_name
from
  kanazawa_market_salted_dried_fish_raw_data;

create table
  market (
    id int generated by default as identity primary key,
    year int not null,
    product_id int not null,
    prefecture_id int not null,
    quantity int8 not null,
    amount int8 not null,
    foreign key (product_id) references products (product_id),
    foreign key (prefecture_id) references prefectures (prefecture_id)
  );

insert into
  market (year, product_id, prefecture_id, quantity, amount)
select
  cast(year as integer),
  product_id,
  prefecture_id,
  cast(replace(quantity, ',', '') as int8),
  cast(replace(amount, ',', '') as int8)
from
  (
    select
      year,
      (
        select
          product_id
        from
          products
        where
          freeze_fish.product_name = products.name
      ),
      (
        select
          prefecture_id
        from
          prefectures
        where
          freeze_fish.producing_area = prefectures.name
      ),
      quantity,
      amount
    from
      kanazawa_market_freeze_fish_raw_data as freeze_fish
    union
    select
      year,
      (
        select
          product_id
        from
          products
        where
          freeze_fish.product_name = products.name
      ),
      (
        select
          prefecture_id
        from
          prefectures
        where
          freeze_fish.producing_area = prefectures.name
      ),
      quantity,
      amount
    from
      kanazawa_market_fresh_fish_raw_data as freeze_fish
    union
    select
      year,
      (
        select
          product_id
        from
          products
        where
          freeze_fish.product_name = products.name
      ),
      (
        select
          prefecture_id
        from
          prefectures
        where
          freeze_fish.producing_area = prefectures.name
      ),
      quantity,
      amount
    from
      kanazawa_market_salted_dried_fish_raw_data as freeze_fish
    order by
      year,
      product_id,
      prefecture_id
  );


drop table
  kanazawa_market_freeze_fish_raw_data,
  kanazawa_market_fresh_fish_raw_data,
  kanazawa_market_salted_dried_fish_raw_data;
